export const data1 = [
  {
    activity_name: 'swimming',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: '150',
    time: '2:30:00 PM',
    timezone: 'CET',
    type: 'swim',
  },
  {
    activity_name: 'picnic',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: '0.00',
    time: '10:30:00 PM',
    timezone: 'CET',
    type: 'picnic',
  },
  {
    activity_name: 'rafting',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 12,
    time: '11:30:00 PM',
    timezone: 'CET',
    type: 'adventure sport',
  },
  {
    activity_name: 'Nature hiking',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 23.99,
    time: '9:30:00 PM',
    timezone: 'CET',
    type: 'hiking',
  },
];

export const data2 = [
  {
    activity_name: 'Paris Hiking',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 11.99,
    time: '2:00:00 PM',
    timezone: 'CET',
    type: 'hiking',
  },
  {
    activity_name: 'testing rocks',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 14.99,
    time: '4:00:00 PM',
    timezone: 'CET',
    type: 'trekking',
  },
  {
    activity_name: 'new adventure',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 12.99,
    time: '6:00:00 PM',
    timezone: 'CET',
    type: 'swimming',
  },
  {
    activity_name: 'meditation',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 24.99,
    time: '7:00:00 PM',
    timezone: 'CET',
    type: 'relaxing',
  },
  {
    activity_name: 'paintball fight',
    img_url: 'https://i.imgur.com/1OE3HSL.png',
    price: 50,
    time: '10:00:00 PM',
    timezone: 'CET',
    type: 'playing',
  },
];

export const data3 = [
  {
    activity_name: 'A la Francais',
    img_url: 'https://i.imgur.com/1OE3HSL.png',
    price: 20,
    time: '10:00:00 AM',
    timezone: 'CET',
    type: 'food',
  },
  {
    activity_name: 'Paris Hiking Trail',
    img_url: 'https://i.imgur.com/1OE3HSL.png',
    price: 10,
    time: '12:00:00 PM',
    timezone: 'CET',
    type: 'hiking',
  },
  {
    activity: 'Hilton Hotel',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 25.5,
    time: '2:00:00 PM',
    timezone: 'CET',
    type: 'hotel',
  },
  {
    activity_name: 'Spa in Paris',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 50,
    time: '5:00:00 PM',
    timezone: 'CET',
    type: 'spa',
  },
  {
    activity_name: 'Baguettes',
    img_url: 'https://i.imgur.com/iGoLKkO.png',
    price: 10,
    time: '9:00:00 PM',
    timezone: 'CET',
    type: 'food',
  },
];
export const data4 = [
  {
    activity_name: 'Beach swim',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 0,
    time: "9:00:00 AM",
    timezone: 'CET',
    type: 'swimming',
  },
  {
    activity_name: 'Scuba diving',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 101.99,
    time: "11:00:00 AM",
    timezone: 'CET',
    type: 'swimming',
  },
  {
    activity_name: 'Baguettes',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 12.99,
    time: "9:00:00 PM",
    timezone: 'CET',
    type: 'food',
  },
];
export const data5 = [
  {
    activity_name: 'return flight',
    img_url: 'https://i.imgur.com/pMbdjhZ.png',
    price: 1050,
    time: "9:00:00 AM",
    timezone: 'CET',
    type: 'commuting',
  },
];
